config/routes.rb
Rails.application.routes.draw do
	root 'main#top'
  resources :users

  resource :admin_view, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circle.rb
class Circle < ApplicationRecord
  has_many :circle_users
  has_many :users, through: :circle_users
end

app/models/circle_user.rb
class CircleUser < ApplicationRecord
  belongs_to :user
  belongs_to :circle
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/Main_controller.rb
class MainController < ApplicationController
  def top
    @users = User.all
  end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
end

app/controllers/admin_views_controller.rb
class AdminViewsController < AdminController
  def show; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'userを作成できました。'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :blood_type, :is_married)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_views/show.html.erb
AdminControllerが読み込まれてます。

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgramanDojo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>【プログラマン道場】 管理画面</h1>
    </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgramanDojo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>【プログラマン道場】</h1>
      <h2>enumを理解しよう！！</h2>
    </header>
    <%= yield %>
  </body>
</html>

app/views/main/search.html.erb
<div class='p-top'>
  <div class='p-top__title'><%= link_to "ユーザー登録", new_user_path %></div>
  <table border="1" class= 'p-top__introduce'>
    <tr>
    <th>名前</th>
    <th>年齢</th>
    <th>身長</th>
    <th>体重</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
      <td><%= user.name%></td>
      <td><%= "#{user.age}歳" %></td>
      <td><%= "#{user.tall}cm" %></td>
      <td><%= "#{user.weight}kg" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/main/top.html.erb
<div class='p-top'>
  <table border="1" class= 'p-top__introduce'>
    <tr>
    <th>名前</th>
    <th>年齢</th>
    <th>血液型</th>
    <th>婚姻関係？</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
      <td><%= user.name %></td>
      <td><%= "#{user.age}歳" %></td>
      <td><%= "#{user.blood_type}型" %></td>
      <td><%= user.is_married? ? '既婚' : '未婚' %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/index.html.erb
<div class='p-top'>
<table border="1" class= 'p-top__introduce'>
    <tr>
    <th>id</th>
    <th>名前</th>
    <th>年齢</th>
    <th>身長</th>
    <th>体重</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
      <td><%= user.id %></td>
      <td><%= user.name%></td>
      <td><%= "#{user.age}歳" %></td>
      <td><%= "#{user.tall}cm" %></td>
      <td><%= "#{user.weight}kg" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<div class="wrapper" style="text-align: center;">
  <% if @user.errors.any? %>
    <p class="alert alert-danger" style="width: 500px; margin: 0 auto;"><%= @user.errors.full_messages %></p>
  <% end %>
  <%= form_for(@user, :html => {:style => "width: 500px; margin: 30px auto;"}) do |f| %>
    <div class="form-group" style="margin-bottom: 30px;">
      <label style="text-align: left; display: block;">名前</label>
      <%= f.text_field :name, class: 'form-control', style: 'margin-bottom: 15px;'%>
      <label style="text-align: left; display: block;">年齢</label>
      <%= f.text_field :age, class: 'form-control', style: 'margin-bottom: 15px;'%>
      <label style="text-align: left; display: block;">血液型</label>
      <%= f.select :blood_type, User.blood_types.keys.map {|k| [k, k]}, {}, { class: 'form-control', style: 'margin-bottom: 15px;', data: {} } %>
      <label style="text-align: left; display: block;">婚姻関係</label>
      <%= f.select :is_married, [['未婚', false], ['既婚', true]], {}, { class: 'form-control', data: {} } %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='p-top'>
</div>
    <table border="1" class= 'p-top__introduce'>
    <tr>
    <th>id</th>
    <th>名前</th>
    <th>年齢</th>
    <th>身長</th>
    <th>体重</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
      <td><%= user.id %></td>
      <td><%= user.name%></td>
      <td><%= "#{user.age}歳" %></td>
      <td><%= "#{user.tall}cm" %></td>
      <td><%= "#{user.weight}kg" %></td>
      </tr>
    <% end %>
  </table>
</div>